name: Docker Image CI

on:
  push:
    branches:
    - master
    
    paths:
    - '*.cs'    
    - '*.csproj'
    - '*.sln'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker login --username slado --password ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag slado/helloworldapi:${GITHUB_SHA}
        docker push slado/helloworldapi:${GITHUB_SHA}
      env:
        IMAGE_TAG: $(date +%s)
        
