name: Docker Image branch CI

on:
  push:
    branches:
    - dev*

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image for branch
      run: | 
        docker login --username slado --password ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag slado/helloworldapi:${GITHUB_REF}
        docker push slado/helloworldapi:${GITHUB_REF}
