name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker build . --file Dockerfile --tag HelloWorldAPI:$(date +%s)
        push docker.pkg.github.com/$GITHUB_REPOSITORY/HelloWorldAPI:$(date +%s)
