name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker login --username slado --password ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag slado/helloworldapi:${IMAGE_TAG}
        docker push slado/helloworldapi:${IMAGE_TAG}
        docker push slado/helloworldapi:latest
      env:
        IMAGE_TAG: $(date +%s)
        
